class MYOBScope:
    SM_GENERAL_LEDGER = "sme-general-ledger"
    SM_SALES = "sme-sales"
    SM_TIMEBILLING = "sme-timebilling"
    SM_INVENTORY = "sme-inventory"
    SM_CONTACTS_CUSTOMER = "sme-contacts-customer"
    SM_CONTACTS_SUPPLIER = "sme-contacts-supplier"
    SM_CONTACTS_PERSONAL = "sme-contacts-personal"
    SM_CONTACTS_EMPLOYEE = "sme-contacts-employee"
    SM_BANKING = "sme-banking"
    SM_PURCHASES = "sme-purchases"
    SM_PAYROLL = "sme-payroll"
    SM_COMPANY_SETTINGS = "sme-company-settings"
    SM_COMPANY_FILE = "sme-company-file"
